/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_11 (
    input [4:0] char,
    output reg [7:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      8'h00: begin
        segs = 8'hc0;
      end
      8'h01: begin
        segs = 8'hf9;
      end
      8'h02: begin
        segs = 8'ha4;
      end
      8'h03: begin
        segs = 8'hb0;
      end
      8'h04: begin
        segs = 8'h99;
      end
      8'h05: begin
        segs = 8'h92;
      end
      8'h06: begin
        segs = 8'h82;
      end
      8'h07: begin
        segs = 8'hf8;
      end
      8'h08: begin
        segs = 8'h80;
      end
      8'h09: begin
        segs = 8'h90;
      end
      8'h0a: begin
        segs = 8'h88;
      end
      8'h0b: begin
        segs = 8'h83;
      end
      8'h0c: begin
        segs = 8'hc6;
      end
      8'h0d: begin
        segs = 8'ha1;
      end
      8'h0e: begin
        segs = 8'h86;
      end
      8'h0f: begin
        segs = 8'h8e;
      end
      8'h10: begin
        segs = 8'haf;
      end
      8'h11: begin
        segs = 8'he3;
      end
      8'h12: begin
        segs = 8'h87;
      end
      default: begin
        segs = 8'hff;
      end
    endcase
  end
endmodule
