/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_select_value_6 (
    input [1:0] in,
    input [14:0] value,
    output reg [7:0] out
  );
  
  
  
  wire [8-1:0] M_seg_segs;
  reg [5-1:0] M_seg_char;
  seven_seg_11 seg (
    .char(M_seg_char),
    .segs(M_seg_segs)
  );
  
  always @* begin
    M_seg_char = 1'h0;
    
    case (in)
      2'h0: begin
        M_seg_char = value[0+4-:5];
        out = M_seg_segs;
      end
      2'h1: begin
        M_seg_char = value[5+4-:5];
        out = M_seg_segs;
      end
      2'h2: begin
        M_seg_char = value[10+4-:5];
        out = M_seg_segs;
      end
      default: begin
        out = 8'hff;
      end
    endcase
  end
endmodule
