/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module booleanUnit_14 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn_signal,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (alufn_signal[0+3-:4])
      4'h8: begin
        out = a & b;
      end
      4'h9: begin
        out = !(a & b);
      end
      4'he: begin
        out = a | b;
      end
      4'hf: begin
        out = !(a | b);
      end
      4'h6: begin
        out = a ^ b;
      end
      4'h7: begin
        out = !(a ^ b);
      end
      4'ha: begin
        out = a;
      end
      4'hb: begin
        out = !a;
      end
      4'hc: begin
        out = b;
      end
      4'hd: begin
        out = !b;
      end
      default: begin
        out = 32'h00000000;
      end
    endcase
  end
endmodule
