/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module errorChecker_10 (
    input [5:0] alufn_signal,
    output reg [0:0] out
  );
  
  
  
  always @* begin
    
    case (alufn_signal[4+1-:2])
      2'h0: begin
        out = 1'h0;
        if (alufn_signal[1+2-:3] != 3'h0) begin
          out = 1'h1;
        end
      end
      2'h1: begin
        out = 1'h0;
        if (alufn_signal[0+3-:4] <= 4'h5) begin
          out = 1'h1;
        end
      end
      2'h2: begin
        out = 1'h1;
        if (alufn_signal[0+3-:4] <= 4'h3) begin
          if (alufn_signal[0+1-:2] != 2'h2) begin
            out = 1'h0;
          end
        end
      end
      2'h3: begin
        out = 1'h1;
        if (alufn_signal[0+3-:4] == 4'h3 || alufn_signal[0+3-:4] == 4'h5 || alufn_signal[0+3-:4] == 4'h7) begin
          out = 1'h0;
        end
      end
      default: begin
        out = 1'h1;
      end
    endcase
  end
endmodule
